# dbt_project.yml
name: 'ethiopian_medical_project'
version: '1.0'
config-version: 2

profile: 'ethiopian_medical_profile'

model-paths: ["models"]
macro-paths: ["macros"]
data-paths: ["data"]
test-paths: ["tests"]

models:
  ethiopian_medical_project:
    cleaned_data:
      materialized: view
